version: "3.7"
services:

  db:
    image: mysql:8.0.22
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: sirens_bot


  sirens-discord-bot:
    build: .
    restart: on-failure
    ports:
      - 80:80
    depends_on:
      - db